name = "refresheet-prj"
compatibility_date = "2026-05-04"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "db_game_info"
database_id = "5c560a75-93a5-4414-88fc-0bd8e9ff4e26"
migrations_dir = "docs/migrations"
